# Generated by Django 5.2.5 on 2025-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField()),
                ('address_area', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_type', models.CharField(max_length=50)),
                ('base_policy', models.CharField(max_length=50)),
                ('number_of_cars', models.PositiveIntegerField(default=1)),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('vehicle_price_category', models.CharField(blank=True, max_length=50, null=True)),
                ('age_of_vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_vehicle', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('past_number_of_claims', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
