# Generated by Django 5.2.6 on 2025-10-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('claim_description', models.TextField()),
                ('accident_date', models.DateField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dl_number', models.CharField(max_length=50, verbose_name='Driving License Number')),
                ('vehicle_reg_no', models.CharField(max_length=50, verbose_name='Vehicle Registration Number')),
                ('fir_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='FIR Number')),
                ('total_images_submitted', models.PositiveIntegerField(default=1)),
                ('image_paths', models.JSONField(blank=True, default=list)),
                ('fraud_detected', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence score as percentage (0-100)', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Verified', 'Verified/Claimed'), ('Fraud', 'Fraud Detected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('tabular_fraud_probability', models.DecimalField(blank=True, decimal_places=2, help_text='Tabular model fraud probability %', max_digits=5, null=True)),
                ('image_fraud_probability', models.DecimalField(blank=True, decimal_places=2, help_text='Image model fraud probability %', max_digits=5, null=True)),
                ('fusion_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final fusion score %', max_digits=5, null=True)),
                ('overall_damage_severity', models.CharField(blank=True, choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity')], max_length=10, null=True)),
                ('total_damage_areas', models.PositiveIntegerField(default=0)),
                ('average_damage_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Average damage coverage across all images', max_digits=5, null=True)),
                ('max_fraud_image_index', models.PositiveIntegerField(blank=True, null=True)),
                ('max_fraud_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fraud_probability_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fraud_probability_std', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dl_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rto_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fir_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verification_reliability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detailed_analysis', models.JSONField(blank=True, default=dict, help_text='Complete JSON response from fraud detection API')),
                ('annotated_images', models.JSONField(blank=True, default=list, help_text='List of annotated damage detection images')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='detection.policyholder')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Claim Submitted'), ('analyzed', 'AI Analysis Completed'), ('reviewed', 'Admin Reviewed'), ('status_changed', 'Status Changed'), ('approved', 'Claim Approved'), ('rejected', 'Claim Rejected')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='detection.claim')),
            ],
            options={
                'verbose_name': 'Claim History',
                'verbose_name_plural': 'Claim Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClaimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index', models.PositiveIntegerField()),
                ('image_file', models.ImageField(upload_to='claim_images/%Y/%m/%d/')),
                ('fraud_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('damage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity_level', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity')], max_length=10)),
                ('damage_areas_count', models.PositiveIntegerField(default=0)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated_images/%Y/%m/%d/')),
                ('damage_regions', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='detection.claim')),
            ],
            options={
                'ordering': ['image_index'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', '-submitted_at'], name='detection_c_status_9006c8_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policyholder', '-submitted_at'], name='detection_c_policyh_b2aa81_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['fraud_detected', 'status'], name='detection_c_fraud_d_557e55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claimimage',
            unique_together={('claim', 'image_index')},
        ),
    ]
