# Generated by Django 5.2.6 on 2025-12-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='vehicle_model',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
