# Generated by Django 5.2.6 on 2026-02-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_policyholder_vehicle_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyorFieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='surveyor_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Surveyor Field Photo',
                'verbose_name_plural': 'Surveyor Field Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('surveyor', 'Surveyor')], default='customer', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_region', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='assigned_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Surveyor'),
        ),
        migrations.AddField(
            model_name='claim',
            name='damage_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Damage Verified on Site'),
        ),
        migrations.AddField(
            model_name='claim',
            name='max_damage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Survey Completion Time'),
        ),
        migrations.AddField(
            model_name='claim',
            name='surveyor_assessed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surveyor Assessed Amount'),
        ),
        migrations.AddField(
            model_name='claim',
            name='surveyor_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Field Survey Notes'),
        ),
        migrations.AddField(
            model_name='claim',
            name='surveyor_recommendation',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approve Claim'), ('REJECT', 'Reject Claim'), ('INVESTIGATE', 'Further Investigation'), ('PARTIAL', 'Partial Approval')], max_length=20, null=True, verbose_name='Surveyor Recommendation'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='annotated_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='claim',
            name='average_damage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='claim',
            name='detailed_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='claim',
            name='fusion_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='image_fraud_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Under Survey', 'Under Survey'), ('Survey Completed', 'Survey Completed'), ('Verified', 'Verified/Claimed'), ('Fraud', 'Fraud Detected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='tabular_fraud_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='claimhistory',
            name='action',
            field=models.CharField(choices=[('submitted', 'Claim Submitted'), ('analyzed', 'AI Analysis Completed'), ('reviewed', 'Admin Reviewed'), ('status_changed', 'Status Changed'), ('approved', 'Claim Approved'), ('rejected', 'Claim Rejected'), ('surveyor_assigned', 'Surveyor Assigned'), ('survey_started', 'Field Survey Started'), ('survey_completed', 'Field Survey Completed'), ('surveyor_report', 'Surveyor Report Submitted')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_surveyor', 'status'], name='detection_c_assigne_a7281d_idx'),
        ),
        migrations.AddField(
            model_name='surveyorfieldphoto',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_photos', to='detection.claim'),
        ),
        migrations.AddField(
            model_name='surveyorfieldphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
