# Generated by Django 5.2.6 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_surveyorfieldphoto_userprofile_claim_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Required when claim is rejected – will be visible to the customer.', null=True, verbose_name='Rejection Reason'),
        ),
    ]
