# Generated by Django 5.2.6 on 2026-02-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_add_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='fraud_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='SHAP or rule-based fraud explanation factors'),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_summary',
            field=models.TextField(blank=True, help_text='One-line human readable fraud summary for admin', null=True),
        ),
    ]
