# Generated by Django 5.2.6 on 2026-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_add_fraud_explanation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='fraud_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='claim',
            name='fraud_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
