# Generated by Django 5.2.6 on 2026-02-27 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_alter_claim_fraud_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('location', models.TextField(help_text='Address or location for the survey visit')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the appointment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_preferences', models.JSONField(blank=True, default=dict, help_text="Customer's preferred time slots")),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='detection.claim')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to=settings.AUTH_USER_MODEL)),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_datetime'],
                'indexes': [models.Index(fields=['claim', 'status'], name='detection_a_claim_i_60f42b_idx'), models.Index(fields=['customer', 'status'], name='detection_a_custome_205550_idx'), models.Index(fields=['surveyor', 'status'], name='detection_a_surveyo_35c5c5_idx'), models.Index(fields=['proposed_datetime'], name='detection_a_propose_9e91bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_appointments', models.PositiveIntegerField(default=1)),
                ('current_appointments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['surveyor', 'date', 'is_available'], name='detection_a_surveyo_928beb_idx')],
                'unique_together': {('surveyor', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('appointment', 'Appointment'), ('system', 'System')], default='text', max_length=20)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='detection.claim')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['claim', 'timestamp'], name='detection_c_claim_i_f9dfac_idx'), models.Index(fields=['sender', 'recipient'], name='detection_c_sender__55f7b2_idx')],
            },
        ),
    ]
